<?php

namespace AppBundle\Repository;

/**
 * CompanyBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
