<?php

namespace AppBundle\Repository;

/**
 * ProductFactoredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductFactoredRepository extends \Doctrine\ORM\EntityRepository
{
}
