<?php

namespace AppBundle\Repository;

/**
 * WarehouseCellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseCellRepository extends \Doctrine\ORM\EntityRepository
{
}
