imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
#    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    serializer:
        enabled: true

    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    AppBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_menu:
    twig:
        template: AppBundle:Default:knp_menu.html.twig

sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.admin.block.search_result:
            contexts:   [admin]

#        sonata.admin_doctrine_orm.block.audit:
#            contexts:   [admin]
#
#        sonata.block.service.text:
#            contexts:   [admin]
#
#        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

        # Some block with different templates
        #acme.demo.block.demo:
        #    templates:
        #       - { name: 'Simple', template: 'AcmeDemoBundle:Block:demo_simple.html.twig' }
        #       - { name: 'Big',    template: 'AcmeDemoBundle:Block:demo_big.html.twig' }

sonata_admin:
    title: Schedro
    title_logo: /images/logo_title_small.png
    templates:
        user_block:           ZorbusAdminThemeBundle:Core:user_block.html.twig
        add_block:            ZorbusAdminThemeBundle:Core:add_block.html.twig
        layout:               ZorbusAdminThemeBundle::standard_layout.html.twig
        ajax:                 ZorbusAdminThemeBundle::ajax_layout.html.twig
        dashboard:            ZorbusAdminThemeBundle:Core:dashboard.html.twig
        search:               ZorbusAdminThemeBundle:Core:search.html.twig
        list:                 ZorbusAdminThemeBundle:CRUD:list.html.twig
        filter:               ZorbusAdminThemeBundle:Form:filter_admin_fields.html.twig
        show:                 ZorbusAdminThemeBundle:CRUD:show.html.twig
        show_compare:         ZorbusAdminThemeBundle:CRUD:show_compare.html.twig
        edit:                 ZorbusAdminThemeBundle:CRUD:edit.html.twig
        preview:              ZorbusAdminThemeBundle:CRUD:preview.html.twig
        history:              ZorbusAdminThemeBundle:CRUD:history.html.twig
        acl:                  ZorbusAdminThemeBundle:CRUD:acl.html.twig
        history_revision_timestamp:  ZorbusAdminThemeBundle:CRUD:history_revision_timestamp.html.twig
        action:               ZorbusAdminThemeBundle:CRUD:action.html.twig
        select:               ZorbusAdminThemeBundle:CRUD:list__select.html.twig
        list_block:           ZorbusAdminThemeBundle:Block:block_admin_list.html.twig
        search_result_block:  ZorbusAdminThemeBundle:Block:block_search_result.html.twig
        short_object_description:  ZorbusAdminThemeBundle:Helper:short-object-description.html.twig
        delete:               ZorbusAdminThemeBundle:CRUD:delete.html.twig
        batch:                ZorbusAdminThemeBundle:CRUD:list__batch.html.twig
        batch_confirmation:   ZorbusAdminThemeBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:       ZorbusAdminThemeBundle:CRUD:list_inner_row.html.twig
        base_list_field:      ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
        pager_links:          ZorbusAdminThemeBundle:Pager:links.html.twig
        pager_results:        ZorbusAdminThemeBundle:Pager:results.html.twig
        tab_menu_template:    ZorbusAdminThemeBundle:Core:tab_menu_template.html.twig
    assets:
        stylesheets:
            - bundles/zorbusadmintheme/css/bootstrap.min.css
            - bundles/zorbusadmintheme/css/plugins/metisMenu/metisMenu.min.css
            - bundles/zorbusadmintheme/css/plugins/timeline.css
            - bundles/zorbusadmintheme/css/sb-admin-2.css
            - bundles/zorbusadmintheme/css/plugins/morris.css
            - bundles/zorbusadmintheme/font-awesome/css/font-awesome.min.css
        javascripts:
            - bundles/zorbusadmintheme/js/jquery.js
            - bundles/zorbusadmintheme/js/bootstrap.min.js
            - bundles/zorbusadmintheme/js/plugins/metisMenu/metisMenu.min.js
            - bundles/zorbusadmintheme/js/sb-admin-2.js

sonata_doctrine_orm_admin:
    templates:
        form:
            - ZorbusAdminThemeBundle:Form:form_admin_fields.html.twig
        filter:
            - ZorbusAdminThemeBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      ZorbusAdminThemeBundle:CRUD:list_array.html.twig
                boolean:    ZorbusAdminThemeBundle:CRUD:list_boolean.html.twig
                date:       ZorbusAdminThemeBundle:CRUD:list_date.html.twig
                time:       ZorbusAdminThemeBundle:CRUD:list_time.html.twig
                datetime:   ZorbusAdminThemeBundle:CRUD:list_datetime.html.twig
                text:       ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
                trans:      ZorbusAdminThemeBundle:CRUD:list_trans.html.twig
                string:     ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
                smallint:   ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
                bigint:     ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
                integer:    ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
                decimal:    ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
                identifier: ZorbusAdminThemeBundle:CRUD:base_list_field.html.twig
                currency:   ZorbusAdminThemeBundle:CRUD:list_currency.html.twig
                percent:    ZorbusAdminThemeBundle:CRUD:list_percent.html.twig
                choice:     ZorbusAdminThemeBundle:CRUD:list_choice.html.twig
                url:        ZorbusAdminThemeBundle:CRUD:list_url.html.twig

            show:
                array:      ZorbusAdminThemeBundle:CRUD:show_array.html.twig
                boolean:    ZorbusAdminThemeBundle:CRUD:show_boolean.html.twig
                date:       ZorbusAdminThemeBundle:CRUD:show_date.html.twig
                time:       ZorbusAdminThemeBundle:CRUD:show_time.html.twig
                datetime:   ZorbusAdminThemeBundle:CRUD:show_datetime.html.twig
                text:       ZorbusAdminThemeBundle:CRUD:base_show_field.html.twig
                trans:      ZorbusAdminThemeBundle:CRUD:show_trans.html.twig
                string:     ZorbusAdminThemeBundle:CRUD:base_show_field.html.twig
                smallint:   ZorbusAdminThemeBundle:CRUD:base_show_field.html.twig
                bigint:     ZorbusAdminThemeBundle:CRUD:base_show_field.html.twig
                integer:    ZorbusAdminThemeBundle:CRUD:base_show_field.html.twig
                decimal:    ZorbusAdminThemeBundle:CRUD:base_show_field.html.twig
                currency:   ZorbusAdminThemeBundle:CRUD:base_currency.html.twig
                percent:    ZorbusAdminThemeBundle:CRUD:base_percent.html.twig
                choice:     ZorbusAdminThemeBundle:CRUD:show_choice.html.twig
                url:        ZorbusAdminThemeBundle:CRUD:show_url.html.twig