# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
    fos_user.doctrine_registry:
        alias: doctrine

    admin.country:
        class: AppBundle\Admin\CountryAdmin
        arguments: [~, AdminBundle\Entity\Country, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Country }

    admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [~, AdminBundle\Entity\City, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: City }

    admin.user_group:
        class: AppBundle\Admin\UserGroupAdmin
        arguments: [~, UserBundle\Entity\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User Group}

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }