<?php

namespace AdminBundle\Repository;

/**
 * DistributionCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionCenterRepository extends \Doctrine\ORM\EntityRepository
{
}
