<?php

namespace AdminBundle\Repository;

/**
 * EmployeeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
