<?php

namespace AdminBundle\Repository;

/**
 * userCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
