<?php

namespace AdminBundle\Repository;

/**
 * FactoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactoryRepository extends \Doctrine\ORM\EntityRepository
{
}
