<?php

namespace AdminBundle\Repository;

/**
 * ProportionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProportionRepository extends \Doctrine\ORM\EntityRepository
{
}
