<?php

namespace AdminBundle\Repository;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends \Doctrine\ORM\EntityRepository
{
//    /**
//     * Get isWeight
//     *
//     * @return bool
//     */
//    public function isWeight()
//    {
//        return $this->isWeight;
//    }
//
//    /**
//     * Get isArea
//     *
//     * @return bool
//     */
//    public function isArea()
//    {
//        return $this->isArea;
//    }
//
//    /**
//     * Get isVolume
//     *
//     * @return bool
//     */
//    public function isVolume()
//    {
//        return $this->isVolume;
//    }
//
//    /**
//     * Get isModifiable
//     *
//     * @return bool
//     */
//    public function isModifiable()
//    {
//        return $this->isModifiable;
//    }
//
//    /**
//     * Get isVisible
//     *
//     * @return bool
//     */
//    public function isVisible()
//    {
//        return $this->isVisible;
//    }
}
